# Generated by Django 5.0 on 2023-12-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_task_table_alter_type_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='types',
            new_name='type',
        ),
    ]
