# Generated by Django 5.0 on 2023-12-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_types_task_typesя'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='typesя',
            new_name='types',
        ),
    ]
