# Generated by Django 5.0 on 2024-01-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_project_user_alter_task_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='users',
        ),
    ]
